#!/usr/bin/env python3
"""
Seed script for recommended plants.
Run this script to populate the database with beginner-friendly plants.

Usage: python scripts/seed_recommended_plants.py
"""

import asyncio
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database import Database


# Recommended plants data
RECOMMENDED_PLANTS = [
   {
      "plant_id":"tulsi",
      "common_name":"Tulsi",
      "scientific_name":"Ocimum sanctum",
      "image_url":"https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Daily",
      "description":"Sacred plant with medicinal properties. Essential for puja and natural remedies.",
      "success_rate":96,
      "quick_benefit":"Sacred & medicinal",
      "price_range":"₹50-150",
      "google_search_term":"Tulsi plant nursery near me",
      "care_tip":"Prefers morning sunlight, keep soil moist",
      "growth_speed":"medium",
      "is_beginner_friendly":True,
      "order":1
   },
   {
      "plant_id":"money_plant",
      "common_name":"Money Plant",
      "scientific_name":"Epipremnum aureum",
      "image_url":"https://images.unsplash.com/photo-1637967886160-fd78dc3ce3f5?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 4-5 days",
      "description":"Air-purifying vine that thrives in low light. Symbol of prosperity and good luck.",
      "success_rate":95,
      "quick_benefit":"Thrives in low light",
      "price_range":"₹100-250",
      "google_search_term":"Money plant nursery near me",
      "care_tip":"Water when top soil feels dry",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":2
   },
   {
      "plant_id":"snake_plant",
      "common_name":"Snake Plant",
      "scientific_name":"Sansevieria trifasciata",
      "image_url":"https://images.unsplash.com/photo-1593482892290-f54927ae1bb6?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 2-3 weeks",
      "description":"Nearly indestructible! Tolerates neglect and purifies air 24/7.",
      "success_rate":98,
      "quick_benefit":"Tolerates neglect",
      "price_range":"₹150-350",
      "google_search_term":"Snake plant nursery near me",
      "care_tip":"Water only when soil is completely dry",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":3
   },
   {
      "plant_id":"jade_plant",
      "common_name":"Jade Plant",
      "scientific_name":"Crassula ovata",
      "image_url":"https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 weeks",
      "description":"Succulent that symbolizes prosperity. Stores water in thick leaves.",
      "success_rate":94,
      "quick_benefit":"Symbol of prosperity",
      "price_range":"₹150-400",
      "google_search_term":"Jade plant nursery near me",
      "care_tip":"Needs bright light, minimal watering",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":4
   },
   {
      "plant_id":"aloe_vera",
      "common_name":"Aloe Vera",
      "scientific_name":"Aloe barbadensis miller",
      "image_url":"https://images.unsplash.com/photo-1596547609652-9cf5d8c76921?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 weeks",
      "description":"Medicinal gel for burns and skin. Hardy succulent that loves sunshine.",
      "success_rate":93,
      "quick_benefit":"Medicinal gel",
      "price_range":"₹80-200",
      "google_search_term":"Aloe vera plant nursery near me",
      "care_tip":"Bright indirect light, let soil dry completely",
      "growth_speed":"medium",
      "is_beginner_friendly":True,
      "order":5
   },
   {
      "plant_id":"spider_plant",
      "common_name":"Spider Plant",
      "scientific_name":"Chlorophytum comosum",
      "image_url":"https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=400",
      "difficulty":"easy",
      "light_needs":"medium",
      "water_frequency":"Every 5-7 days",
      "description":"Produces baby plants you can share. Excellent air purifier.",
      "success_rate":95,
      "quick_benefit":"Produces babies",
      "price_range":"₹100-250",
      "google_search_term":"Spider plant nursery near me",
      "care_tip":"Bright indirect light, keep soil slightly moist",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":6
   },
   {
      "plant_id":"areca_palm",
      "common_name":"Areca Palm",
      "scientific_name":"Dypsis lutescens",
      "image_url":"https://images.unsplash.com/photo-1596003906949-67221c37965c?w=400",
      "difficulty":"easy",
      "light_needs":"medium",
      "water_frequency":"Every 3-4 days",
      "description":"NASA-recommended air purifier. Adds tropical elegance to any room.",
      "success_rate":90,
      "quick_benefit":"Air purifying",
      "price_range":"₹300-800",
      "google_search_term":"Areca palm nursery near me",
      "care_tip":"Keep soil consistently moist, mist leaves weekly",
      "growth_speed":"medium",
      "is_beginner_friendly":True,
      "order":7
   },
   {
      "plant_id":"rubber_plant",
      "common_name":"Rubber Plant",
      "scientific_name":"Ficus elastica",
      "image_url":"https://images.unsplash.com/photo-1545241047-6083a3684587?w=400",
      "difficulty":"medium",
      "light_needs":"medium",
      "water_frequency":"Every 7-10 days",
      "description":"Bold glossy leaves that make a statement. Great for corners.",
      "success_rate":89,
      "quick_benefit":"Bold glossy leaves",
      "price_range":"₹200-500",
      "google_search_term":"Rubber plant nursery near me",
      "care_tip":"Wipe leaves weekly, water when top inch is dry",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":8
   },
   {
      "plant_id":"pothos",
      "common_name":"Pothos",
      "scientific_name":"Epipremnum aureum",
      "image_url":"https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 5-7 days",
      "description":"Beautiful trailing vine perfect for shelves and hanging baskets.",
      "success_rate":97,
      "quick_benefit":"Beautiful trailing vine",
      "price_range":"₹100-300",
      "google_search_term":"Pothos plant nursery near me",
      "care_tip":"Versatile, grows in water or soil",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":9
   },
   {
      "plant_id":"peace_lily",
      "common_name":"Peace Lily",
      "scientific_name":"Spathiphyllum",
      "image_url":"https://images.unsplash.com/photo-1616690002178-4f1c26d23734?w=400",
      "difficulty":"medium",
      "light_needs":"low",
      "water_frequency":"Every 5-7 days",
      "description":"Elegant white flowers in low light. Droops when thirsty.",
      "success_rate":88,
      "quick_benefit":"Blooms in low light",
      "price_range":"₹200-400",
      "google_search_term":"Peace lily nursery near me",
      "care_tip":"Water when leaves droop slightly",
      "growth_speed":"medium",
      "is_beginner_friendly":True,
      "order":10
   },
   {
      "plant_id":"zz_plant",
      "common_name":"ZZ Plant",
      "scientific_name":"Zamioculcas zamiifolia",
      "image_url":"https://images.unsplash.com/photo-1632207691143-643e2bdf2719?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 2-3 weeks",
      "description":"Shiny leaves, thrives in any light. Perfect for offices.",
      "success_rate":97,
      "quick_benefit":"Thrives anywhere",
      "price_range":"₹250-600",
      "google_search_term":"ZZ plant nursery near me",
      "care_tip":"Survives on minimal water and light",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":11
   },
   {
      "plant_id":"croton",
      "common_name":"Croton",
      "scientific_name":"Codiaeum variegatum",
      "image_url":"https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 days",
      "description":"Colorful foliage in reds, yellows, and greens. Bright light brings out colors.",
      "success_rate":85,
      "quick_benefit":"Vibrant colorful leaves",
      "price_range":"₹150-350",
      "google_search_term":"Croton plant nursery near me",
      "care_tip":"Bright light for best colors, keep moist",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":12
   },
   {
      "plant_id":"lucky_bamboo",
      "common_name":"Lucky Bamboo",
      "scientific_name":"Dracaena sanderiana",
      "image_url":"https://images.unsplash.com/photo-1604936593550-57bd98725d3f?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Keep in water",
      "description":"Symbol of luck and prosperity. Grows in water or soil.",
      "success_rate":92,
      "quick_benefit":"Grows in water",
      "price_range":"₹80-300",
      "google_search_term":"Lucky bamboo nursery near me",
      "care_tip":"Change water weekly, indirect light",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":13
   },
   {
      "plant_id":"boston_fern",
      "common_name":"Boston Fern",
      "scientific_name":"Nephrolepis exaltata",
      "image_url":"https://images.unsplash.com/photo-1586763930499-e6e96f4837ba?w=400",
      "difficulty":"medium",
      "light_needs":"medium",
      "water_frequency":"Every 2-3 days",
      "description":"Lush hanging plant perfect for bathrooms. Loves humidity.",
      "success_rate":82,
      "quick_benefit":"Loves humidity",
      "price_range":"₹200-450",
      "google_search_term":"Boston fern nursery near me",
      "care_tip":"High humidity, keep soil consistently moist",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":14
   },
   {
      "plant_id":"rose",
      "common_name":"Rose",
      "scientific_name":"Rosa",
      "image_url":"https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Daily",
      "description":"Classic flowering plant. Needs care but rewards with beautiful blooms.",
      "success_rate":78,
      "quick_benefit":"Beautiful flowers",
      "price_range":"₹150-400",
      "google_search_term":"Rose plant nursery near me",
      "care_tip":"Full sun, regular watering and pruning",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":15
   },
   {
      "plant_id":"hibiscus",
      "common_name":"Hibiscus",
      "scientific_name":"Hibiscus rosa-sinensis",
      "image_url":"https://images.unsplash.com/photo-1595073285566-d162d2a82844?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Daily",
      "description":"Tropical flowers in vibrant colors. Popular for puja and hair care.",
      "success_rate":80,
      "quick_benefit":"Large tropical flowers",
      "price_range":"₹100-300",
      "google_search_term":"Hibiscus plant nursery near me",
      "care_tip":"Full sun, water daily in summer",
      "growth_speed":"fast",
      "is_beginner_friendly":False,
      "order":16
   },
   {
      "plant_id":"marigold",
      "common_name":"Marigold",
      "scientific_name":"Tagetes",
      "image_url":"https://images.unsplash.com/photo-1603048955248-c36275d6a6a5?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 days",
      "description":"Auspicious flowers for festivals. Easy to grow, bright blooms.",
      "success_rate":91,
      "quick_benefit":"Festival favorite",
      "price_range":"₹40-120",
      "google_search_term":"Marigold plant nursery near me",
      "care_tip":"Full sun, deadhead spent flowers",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":17
   },
   {
      "plant_id":"jasmine",
      "common_name":"Jasmine",
      "scientific_name":"Jasminum",
      "image_url":"https://images.unsplash.com/photo-1592729645009-b96d1e63d14b?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 days",
      "description":"Fragrant white flowers. Used in puja and hair decoration.",
      "success_rate":83,
      "quick_benefit":"Heavenly fragrance",
      "price_range":"₹150-350",
      "google_search_term":"Jasmine plant nursery near me",
      "care_tip":"Bright light, support for climbing",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":18
   },
   {
      "plant_id":"fiddle_leaf_fig",
      "common_name":"Fiddle Leaf Fig",
      "scientific_name":"Ficus lyrata",
      "image_url":"https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=400",
      "difficulty":"hard",
      "light_needs":"bright",
      "water_frequency":"Every 7-10 days",
      "description":"Instagram-famous plant with large sculptural leaves.",
      "success_rate":72,
      "quick_benefit":"Instagram famous",
      "price_range":"₹500-1500",
      "google_search_term":"Fiddle leaf fig nursery near me",
      "care_tip":"Bright indirect light, don't move often",
      "growth_speed":"slow",
      "is_beginner_friendly":False,
      "order":19
   },
   {
      "plant_id":"bamboo_palm",
      "common_name":"Bamboo Palm",
      "scientific_name":"Chamaedorea seifrizii",
      "image_url":"https://images.unsplash.com/photo-1612363148951-f0fc6e6e6c7c?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 5-7 days",
      "description":"Air-purifying palm perfect for corners. Low maintenance.",
      "success_rate":87,
      "quick_benefit":"Low light palm",
      "price_range":"₹400-1000",
      "google_search_term":"Bamboo palm nursery near me",
      "care_tip":"Low light ok, keep soil slightly moist",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":20
   },
   {
      "plant_id":"english_ivy",
      "common_name":"English Ivy",
      "scientific_name":"Hedera helix",
      "image_url":"https://images.unsplash.com/photo-1621882625315-bdc0e7b0a338?w=400",
      "difficulty":"easy",
      "light_needs":"medium",
      "water_frequency":"Every 5-7 days",
      "description":"Trailing vine perfect for hanging baskets. Air purifying.",
      "success_rate":89,
      "quick_benefit":"Perfect for hanging",
      "price_range":"₹150-300",
      "google_search_term":"English ivy nursery near me",
      "care_tip":"Bright indirect light, mist occasionally",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":21
   },
   {
      "plant_id":"anthurium",
      "common_name":"Anthurium",
      "scientific_name":"Anthurium andraeanum",
      "image_url":"https://images.unsplash.com/photo-1609358905581-e5381612486e?w=400",
      "difficulty":"medium",
      "light_needs":"medium",
      "water_frequency":"Every 5-7 days",
      "description":"Glossy heart-shaped flowers in red or pink. Long-lasting blooms.",
      "success_rate":81,
      "quick_benefit":"Heart-shaped flowers",
      "price_range":"₹300-700",
      "google_search_term":"Anthurium nursery near me",
      "care_tip":"Bright indirect light, high humidity",
      "growth_speed":"slow",
      "is_beginner_friendly":False,
      "order":22
   },
   {
      "plant_id":"cactus_mixed",
      "common_name":"Cactus",
      "scientific_name":"Cactaceae",
      "image_url":"https://images.unsplash.com/photo-1509937528035-ad76254b0356?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 weeks",
      "description":"Low maintenance desert plant. Perfect for sunny windowsills.",
      "success_rate":94,
      "quick_benefit":"Minimal watering",
      "price_range":"₹80-250",
      "google_search_term":"Cactus plant nursery near me",
      "care_tip":"Bright direct light, water sparingly",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":23
   },
   {
      "plant_id":"monstera",
      "common_name":"Monstera",
      "scientific_name":"Monstera deliciosa",
      "image_url":"https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=400",
      "difficulty":"medium",
      "light_needs":"medium",
      "water_frequency":"Every 7-10 days",
      "description":"Swiss cheese plant with iconic split leaves. Statement piece.",
      "success_rate":84,
      "quick_benefit":"Iconic split leaves",
      "price_range":"₹400-1200",
      "google_search_term":"Monstera plant nursery near me",
      "care_tip":"Medium light, let soil dry between waterings",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":24
   },
   {
      "plant_id":"philodendron",
      "common_name":"Philodendron",
      "scientific_name":"Philodendron hederaceum",
      "image_url":"https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 7-10 days",
      "description":"Heart-shaped leaves, trailing or climbing. Very forgiving.",
      "success_rate":93,
      "quick_benefit":"Heart-shaped leaves",
      "price_range":"₹200-500",
      "google_search_term":"Philodendron nursery near me",
      "care_tip":"Low light tolerant, water when dry",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":25
   },
   {
      "plant_id":"dracaena",
      "common_name":"Dracaena",
      "scientific_name":"Dracaena fragrans",
      "image_url":"https://images.unsplash.com/photo-1597305877032-0668b3c8413f?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 7-10 days",
      "description":"Striped leaves on woody stems. Great for offices and homes.",
      "success_rate":90,
      "quick_benefit":"Office favorite",
      "price_range":"₹300-700",
      "google_search_term":"Dracaena plant nursery near me",
      "care_tip":"Low light ok, don't overwater",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":26
   },
   {
      "plant_id":"aglaonema",
      "common_name":"Aglaonema",
      "scientific_name":"Aglaonema",
      "image_url":"https://images.unsplash.com/photo-1585232350370-2871a6b76b8a?w=400",
      "difficulty":"easy",
      "light_needs":"low",
      "water_frequency":"Every 7-10 days",
      "description":"Colorful variegated leaves in pink, red, or silver patterns.",
      "success_rate":91,
      "quick_benefit":"Colorful variegation",
      "price_range":"₹250-600",
      "google_search_term":"Aglaonema nursery near me",
      "care_tip":"Low light, keep soil slightly moist",
      "growth_speed":"slow",
      "is_beginner_friendly":True,
      "order":27
   },
   {
      "plant_id":"bougainvillea",
      "common_name":"Bougainvillea",
      "scientific_name":"Bougainvillea",
      "image_url":"https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 days",
      "description":"Vibrant paper-like flowers. Perfect for balconies and gardens.",
      "success_rate":85,
      "quick_benefit":"Vibrant blooms",
      "price_range":"₹150-400",
      "google_search_term":"Bougainvillea plant nursery near me",
      "care_tip":"Full sun, prune regularly for blooms",
      "growth_speed":"fast",
      "is_beginner_friendly":False,
      "order":28
   },
   {
      "plant_id":"curry_leaf",
      "common_name":"Curry Leaf",
      "scientific_name":"Murraya koenigii",
      "image_url":"https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 days",
      "description":"Essential for South Indian cooking. Fresh leaves always available.",
      "success_rate":80,
      "quick_benefit":"Fresh curry leaves",
      "price_range":"₹100-250",
      "google_search_term":"Curry leaf plant nursery near me",
      "care_tip":"Full sun, keep soil moist",
      "growth_speed":"slow",
      "is_beginner_friendly":False,
      "order":29
   },
   {
      "plant_id":"mint",
      "common_name":"Mint",
      "scientific_name":"Mentha",
      "image_url":"https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400",
      "difficulty":"easy",
      "light_needs":"medium",
      "water_frequency":"Every 2-3 days",
      "description":"Fresh mint for tea and cooking. Grows fast and spreads easily.",
      "success_rate":92,
      "quick_benefit":"Fresh for tea",
      "price_range":"₹40-100",
      "google_search_term":"Mint plant nursery near me",
      "care_tip":"Keep soil moist, pinch to encourage growth",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":30
   },
   {
      "plant_id":"coriander",
      "common_name":"Coriander",
      "scientific_name":"Coriandrum sativum",
      "image_url":"https://images.unsplash.com/photo-1641842344928-77c47f8dd82b?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 2-3 days",
      "description":"Fresh coriander leaves for daily cooking. Easy to grow from seeds.",
      "success_rate":88,
      "quick_benefit":"Fresh for cooking",
      "price_range":"₹30-80",
      "google_search_term":"Coriander plant nursery near me",
      "care_tip":"Partial sun, harvest regularly",
      "growth_speed":"fast",
      "is_beginner_friendly":True,
      "order":31
   },
   {
      "plant_id":"neem",
      "common_name":"Neem",
      "scientific_name":"Azadirachta indica",
      "image_url":"https://images.unsplash.com/photo-1615671524827-c1fe3973b648?w=400",
      "difficulty":"easy",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 days",
      "description":"Medicinal tree with antibacterial properties. Sacred and useful.",
      "success_rate":89,
      "quick_benefit":"Medicinal benefits",
      "price_range":"₹100-300",
      "google_search_term":"Neem plant nursery near me",
      "care_tip":"Full sun, drought tolerant once established",
      "growth_speed":"medium",
      "is_beginner_friendly":True,
      "order":32
   },
   {
      "plant_id":"ashoka",
      "common_name":"Ashoka",
      "scientific_name":"Saraca asoca",
      "image_url":"https://images.unsplash.com/photo-1615671524827-c1fe3973b648?w=400",
      "difficulty":"medium",
      "light_needs":"medium",
      "water_frequency":"Every 3-4 days",
      "description":"Sacred tree with orange-red flowers. Symbol of love and beauty.",
      "success_rate":82,
      "quick_benefit":"Sacred tree",
      "price_range":"₹200-500",
      "google_search_term":"Ashoka tree nursery near me",
      "care_tip":"Partial shade, keep soil moist",
      "growth_speed":"slow",
      "is_beginner_friendly":False,
      "order":33
   },
   {
      "plant_id":"pomegranate",
      "common_name":"Pomegranate",
      "scientific_name":"Punica granatum",
      "image_url":"https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 days",
      "description":"Fruit-bearing plant. Beautiful flowers followed by nutritious fruits.",
      "success_rate":79,
      "quick_benefit":"Fruit bearing",
      "price_range":"₹200-500",
      "google_search_term":"Pomegranate plant nursery near me",
      "care_tip":"Full sun, regular watering during fruiting",
      "growth_speed":"medium",
      "is_beginner_friendly":False,
      "order":34
   },
   {
      "plant_id":"lemon",
      "common_name":"Lemon",
      "scientific_name":"Citrus limon",
      "image_url":"https://images.unsplash.com/photo-1590502593747-42a996133562?w=400",
      "difficulty":"medium",
      "light_needs":"bright",
      "water_frequency":"Every 3-4 days",
      "description":"Fresh lemons at home. Fragrant flowers and useful fruits.",
      "success_rate":77,
      "quick_benefit":"Fresh lemons",
      "price_range":"₹200-600",
      "google_search_term":"Lemon plant nursery near me",
      "care_tip":"Full sun, well-drained soil, fertilize regularly",
      "growth_speed":"slow",
      "is_beginner_friendly":False,
      "order":35
   }
]


async def seed_recommended_plants():
    """Seed the database with recommended plants."""
    print("🌱 Connecting to database...")
    await Database.connect()
    
    collection = Database.get_collection("recommended_plants")
    
    # Check if plants already exist
    existing_count = await collection.count_documents({})
    if existing_count > 0:
        print(f"⚠️  Found {existing_count} existing plants. Clearing collection...")
        await collection.delete_many({})
    
    # Insert plants
    print(f"📝 Inserting {len(RECOMMENDED_PLANTS)} recommended plants...")
    result = await collection.insert_many(RECOMMENDED_PLANTS)
    
    print(f"✅ Successfully seeded {len(result.inserted_ids)} plants!")
    
    # Create index on plant_id
    await collection.create_index("plant_id", unique=True)
    await collection.create_index("order")
    print("📊 Created indexes on plant_id and order")
    
    await Database.disconnect()
    print("🎉 Done!")


if __name__ == "__main__":
    asyncio.run(seed_recommended_plants())
